package Generator;

import java.util.Random;

/**
 * Created by tomasz on 05.02.16.
 */
public class Streets {
    public static String[] streets =
            {"Amber   "  ,"Acorn	   "   ,"Acres    "
            ,"Auburn	"  ,"Anchor	 "   ,"Alcove   "
            ,"Bent	  "  ,"Apple	   "   ,"Arbor    "
            ,"Big	    "  ,"Autumn	 "   ,"Avenue   "
            ,"Birch	  "  ,"Axe	     "   ,"Bank     "
            ,"Blue	  "  ,"Barn	   "   ,"Bayou    "
            ,"Bright	"  ,"Beacon	 "   ,"Bend     "
            ,"Broad	  "  ,"Bear	   "   ,"Bluff    "
            ,"Burning	"  ,"Beaver	 "   ,"Byway    "
            ,"Calm	  "  ,"Berry	   "   ,"Canyon   "
            ,"Cinder	"  ,"Bird	   "   ,"Chase    "
            ,"Clear	  "  ,"Blossom	 "   ,"Circle   "
            ,"Cold	  "  ,"Bluff	   "   ,"Corner   "
            ,"Colonial"  ,"Branch	 "   ,"Court    "
            ,"Cool	  "  ,"Bridge	 "   ,"Cove     "
            ,"Cotton	"  ,"Brook	   "   ,"Crest    "
            ,"Cozy	  "  ,"Butterfly"	  ,"Cut      "
            ,"Crimson	"  ,"Butternut"	  ,"Dale     "
            ,"Crystal	"  ,"Castle	 "   ,"Dell     "
            ,"Dewy	  "  ,"Chestnut "   ,"Drive    "
            ,"Dusty	  "  ,"Cider	   "   ,"Edge     "
            ,"Easy	  "  ,"Cloud	   "   ,"Estates  "
            ,"Emerald	"  ,"Cottage	 "   ,"Falls    "
            ,"Fallen	"  ,"Creek	   "   ,"Farms    "
            ,"Foggy	  "  ,"Crow	   "   ,"Field    "
            ,"Gentle	"  ,"Dale	   "   ,"Flats    "
            ,"Golden	"  ,"Deer	   "   ,"Gardens  "
            ,"Grand	  "  ,"Diamond	 "   ,"Gate     "
            ,"Green	  "  ,"Dove	   "   ,"Glade    "
            ,"Happy	  "  ,"Elk	     "   ,"Glen     "
            ,"Harvest	"  ,"Elm	     "   ,"Grove    "
            ,"Hazy	  "  ,"Embers	 "   ,"Haven    "
            ,"Heather	"  ,"Fawn	   "   ,"Heights  "
            ,"Hidden	"  ,"Feather	 "   ,"Highlands"
            ,"High	  "  ,"Flower	 "   ,"Hollow   "
            ,"Honey	  "  ,"Forest	 "   ,"Isle     "
            ,"Hush	  "  ,"Fox	     "   ,"Jetty    "
            ,"Indian	"  ,"Gate	   "   ,"Journey  "
            ,"Iron	  "  ,"Goat	   "   ,"Knoll    "
            ,"Ivory	  "  ,"Goose	   "   ,"Lace     "
            ,"Jagged	"  ,"Grove	   "   ,"Lagoon   "
            ,"Lazy	  "  ,"Harbor	 "   ,"Landing  "
            ,"Little	"  ,"Hickory	 "   ,"Lane     "
            ,"Lone	  "  ,"Hills	   "   ,"Ledge    "
            ,"Lonely	"  ,"Holly	   "   ,"Manor    "
            ,"Long	  "  ,"Horse	   "   ,"Meadow   "
            ,"Lost	  "  ,"Island	 "   ,"Mews     "
            ,"Merry	  "  ,"Lake	   "   ,"Niche    "
            ,"Middle	"  ,"Lamb	   "   ,"Nook     "
            ,"Misty	  "  ,"Leaf	   "   ,"Orchard  "
            ,"Noble	  "  ,"Log	     "   ,"Pace     "
            ,"Old	    "  ,"Maple	   "   ,"Park     "
            ,"Orange	"  ,"Mill	   "   ,"Pass     "
            ,"Pearl	  "  ,"Mountain "   ,"Path     "
            ,"Pied	  "  ,"Nectar	 "   ,"Pike     "
            ,"Pleasant"  ,"Nest	   "   ,"Place    "
            ,"Pretty	"  ,"Nut	     "   ,"Point    "
            ,"Quaint	"  ,"Oak	     "   ,"Promenade"
            ,"Quaking	"  ,"Panda	   "   ,"Quay     "
            ,"Quiet	  "  ,"Peach	   "   ,"Race     "
            ,"Red	    "  ,"Pebble	 "   ,"Ramble   "
            ,"Rocky	  "  ,"Pine	   "   ,"Ridge    "
            ,"Rose	  "  ,"Pioneer	 "   ,"Road     "
            ,"Rough	  "  ,"Pond	   "   ,"Round    "
            ,"Round	  "  ,"Pony	   "   ,"Rove     "
            ,"Rustic	"  ,"Prairie	 "   ,"Run      "
            ,"Sandy	  "  ,"Pumpkin	 "   ,"Saunter  "
            ,"Shady	  "  ,"Quail	   "   ,"Shoal    "
            ,"Silent	"  ,"Rabbit	 "   ,"Stead    "
            ,"Silver	"  ,"Rise	   "   ,"Street   "
            ,"Sleepy	"  ,"River	   "   ,"Stroll   "
            ,"Small	  "  ,"Robin	   "   ,"Summit   "
            ,"Square	"  ,"Rock	   "   ,"Swale    "
            ,"Still	  "  ,"Shadow	 "   ,"Terrace  "
            ,"Stony	  "  ,"Sky	     "   ,"Trace    "
            ,"Strong	"  ,"Snake	   "   ,"Trail    "
            ,"Sunny	  "  ,"Spring	 "   ,"Trek     "
            ,"Sweet	  "  ,"Squirrel "   ,"Turn     "
            ,"Tawny	  "  ,"Stone	   "   ,"Twist    "
            ,"Tender	"  ,"Swan	   "   ,"Vale     "
            ,"Thunder	"  ,"Timber	 "   ,"Valley   "
            ,"Turning	"  ,"Treasure "   ,"View     "
            ,"Twin	  "  ,"Turtle	 "   ,"Villa    "
            ,"Umber	  "  ,"View	   "   ,"Vista    "
            ,"Velvet	"  ,"Wagon	   "   ,"Wander   "
            ,"White	  "  ,"Willow	 "   ,"Way      "
            ,"Windy	  "  ,"Zephyr	 "   ,"Woods	   "
            ,"Hawthorne Avenue"
            ,"Orange Street"
            ,"Old York Road"
            ,"Sherman Street"
            ,"Jackson Avenue"
            ,"Fulton Street"
            ,"Broad Street West"
            ,"Cedar Street"
            ,"Adams Street"
            ,"Church Road"
            ,"Broadway"
            ,"Aspen Court"
            ,"Ridge Street"
            ,"Delaware Avenue    "
            ,"West Avenue        "
            ,"Hillcrest Drive    "
            ,"Parker Street      "
            ,"Eagle Street       "
            ,"Fairview Avenue    "
            ,"Rose Street        "
            ,"Lincoln Avenue     "
            ,"Vine Street        "
            ,"Brown Street       "
            ,"Park Place         "
            ,"Route 202          "
            ,"Railroad Avenue    "
            ,"6th Street         "
            ,"Pennsylvania Avenue "
            ,"Arch Street        "
            ,"13th Street        "
            ,"Bridge Street      "
            ,"Jones Street       "
            ,"Virginia Street    "
            ,"Forest Street      "
            ,"Maple Lane         "
            ,"Glenwood Avenue    "
            ,"6th Street North   "
            ,"Beechwood Drive    "
            ,"Cedar Court        "
            ,"Willow Lane        "
            ,"Sherwood Drive     "
            ,"Manor Drive        "
            ,"Central Avenue     "
            ,"Buttonwood Drive   "
            ,"State Street       "
            ,"Amherst Street     "
            ,"Cooper Street      "
            ,"Cobblestone Court  "
            ,"Elmwood Avenue     "
            ,"Mulberry Street    "
            ,"5th Street South   "
            ,"Bayberry Drive     "
            ,"Woodland Drive     "
            ,"Church Street North "
            ,"Woodland Avenue    "
            ,"Hillside Drive     "
            ,"Lake Avenue        "
            ,"Route 27           "
            ,"Eagle Road         "
            ,"Mill Street        "
            ,"Summer Street      "
            ,"Route 30           "
            ,"Maiden Lane        "
            ,"Canterbury Court   "
            ,"Country Club Road  "
            ,"8th Street South   "
            ,"Fairview Road      "
            ,"York Street        "
            ,"Roberts Road       "
            ,"Sunset Drive       "
            ,"Crescent Street    "
            ,"Clinton Street     "
            ,"Tanglewood Drive   "
            ,"Roosevelt Avenue   "
            ,"Linden Avenue      "
            ,"Magnolia Court     "
            ,"Cleveland Avenue   "
            ,"Orchard Avenue     "
            ,"Bank Street        "
            ,"Spruce Avenue      "
            ,"State Street East  "
            ,"Homestead Drive    "
            ,"Charles Street     "
            ,"Summit Street      "
            ,"West Street        "
            ,"Ashley Court       "
            ,"Maple Avenue       "
            ,"Hill Street        "
            ,"Lawrence Street    "
            ,"Chestnut Street    "
            ,"Buckingham Drive   "
            ,"Pine Street        "
            ,"Route 32           "
            ,"North Street       "
            ,"8th Avenue         "
            ,"Race Street        "
            ,"Valley Drive       "
            ,"Winding Way        "
            ,"Clay Street        "
            ,"Canterbury Road    "
            ,"School Street      "
            ,"Route 29           "
            ,"Lexington Court    "
            ,"Lakeview Drive     "
            ,"Grant Avenue       "
            ,"Laurel Drive       "
            ,"Shady Lane         "
            ,"Oak Lane           "
            ,"5th Street         "
            ,"York Road          "
            ,"Virginia Avenue    "
            ,"Route 9            "
            ,"Jefferson Avenue   "
            ,"Highland Avenue    "
            ,"11th Street        "
            ,"East Avenue        "
            ,"Heritage Drive     "
            ,"Briarwood Court    "
            ,"Meadow Street      "
            ,"Atlantic Avenue    "
            ,"College Avenue     "
            ,"10th Street        "
            ,"4th Street West    "
            ,"Colonial Avenue    "
            ,"Hickory Street     "
            ,"Park Avenue        "
            ,"Essex Court        "
            ,"River Street       "
            ,"Belmont Avenue     "
            ,"Schoolhouse Lane   "
            ,"Grant Street       "
            ,"Laurel Lane        "
            ,"High Street        "
            ,"Windsor Drive      "
            ,"Rosewood Drive     "
            ,"Street Road        "
            ,"Howard Street      "
            ,"Wood Street        "
            ,"Myrtle Avenue      "
            ,"Briarwood Drive    "
            ,"Holly Court        "
            ,"Arlington Avenue   "
            ,"Grand Avenue       "
            ,"Washington Street  "
            ,"Sycamore Lane      "
            ,"Glenwood Drive     "
            ,"East Street        "
            ,"Hilltop Road       "
            ,"Magnolia Drive     "
            ,"Harrison Street    "
            ,"3rd Street North   "
            ,"Ivy Lane           "
            ,"Hillcrest Avenue   "
            ,"2nd Street         "
            ,"George Street      "
            ,"Lafayette Avenue   "
            ,"Route 4            "
            ,"Deerfield Drive    "
            ,"Pearl Street       "
            ,"Creek Road         "
            ,"Main Street South  "
            ,"Primrose Lane      "
            ,"Main Street West   "
            ,"Edgewood Drive     "
            ,"Route 70           "
            ,"Harrison Avenue    "
            ,"Union Street       "
            ,"Willow Drive       "
            ,"Hawthorne Lane     "
            ,"Prospect Street    "
            ,"Division Street    "
            ,"Aspen Drive        "
            ,"Park Street        "
            ,"Wall Street        "
            ,"Water Street       "
            ,"Ridge Avenue       "
            ,"Laurel Street      "
            ,"Route 41           "
            ,"Madison Court      "
            ,"12th Street East   "
            ,"Chapel Street      "
            ,"Franklin Avenue    "
            ,"Canterbury Drive   "
            ,"Park Drive         "
            ,"Somerset Drive     "
            ,"3rd Street West    "
            ,"Strawberry Lane    "
            ,"King Street        "
            ,"Hillside Avenue    "
            ,"Front Street South "
            ,"Meadow Lane        "
            ,"Canal Street       "
            ,"12th Street        "
            ,"James Street       "
            ,"Route 7            "
            ,"Grove Avenue       "
            ,"Hartford Road      "
            ,"Pin Oak Drive      "
            ,"Madison Street     "
            ,"6th Avenue         "
            ,"Walnut Street      "
            ,"Smith Street       "
            ,"2nd Avenue         "
            ,"Sycamore Street    "
            ,"Clark Street       "
            ,"Fairway Drive      "
            ,"Redwood Drive      "
            ,"Route 2            "
            ,"River Road         "
            ,"Fieldstone Drive   "
            ,"Euclid Avenue      "
            ,"Green Street       "
            ,"Marshall Street    "
            ,"Morris Street      "
            ,"Valley Road        "
            ,"William Street     "
            ,"5th Avenue         "
            ,"Highland Drive     "
            ,"Fawn Lane          "
            ,"Monroe Street      "
            ,"Creekside Drive    "
            ,"Bridle Court       "
            ,"Front Street North "
            ,"Orchard Street     "
            ,"Cambridge Drive    "
            ,"Mulberry Court     "
            ,"4th Street North   "
            ,"Church Street      "
            ,"Taylor Street      "
            ,"1st Avenue         "
            ,"Queen Street       "
            ,"Oak Avenue         "
            ,"5th Street East    "
            ,"Pheasant Run       "
            ,"Main Street        "
            ,"Beech Street       "
            ,"Lafayette Street   "
            ,"5th Street North   "
            ,"Warren Street      "
            ,"Penn Street        "
            ,"Elm Street         "
            ,"Franklin Street    "
            ,"Monroe Drive       "
            ,"Route 5            "
            ,"Locust Street      "
            ,"Route 10           "
            ,"Elm Avenue         "
            ,"Brook Lane         "
            ,"Colonial Drive     "
            ,"Willow Street      "
            ,"Market Street      "
            ,"Lilac Lane         "
            ,"Depot Street       "
            ,"Berkshire Drive    "
            ,"Lexington Drive    "
            ,"Cedar Lane         "
            ,"2nd Street North   "
            ,"Jefferson Court    "
            ,"Jackson Street     "
            ,"Hanover Court      "
            ,"Williams Street    "
            ,"8th Street         "
            ,"Hickory Lane       "
            ,"1st Street         "
            ,"Ridge Road         "
            ,"Route 1            "
            ,"4th Avenue         "
            ,"Valley View Road   "
            ,"Cambridge Court    "
            ,"Woodland Road      "
            ,"Orchard Lane       "
            ,"Mulberry Lane      "
            ,"Cambridge Road     "
            ,"Route 64           "
            ,"Dogwood Lane       "
            ,"6th Street West    "
            ,"Walnut Avenue      "
            ,"Henry Street       "
            ,"Brookside Drive    "
            ,"Linda Lane         "
            ,"3rd Avenue         "
            ,"Sycamore Drive     "
            ,"Chestnut Avenue    "
            ,"8th Street West    "
            ,"Evergreen Lane     "
            ,"Heather Lane       "
            ,"Main Street North  "
            ,"John Street        "
            ,"Country Club Drive "
            ,"Sunset Avenue      "
            ,"Cherry Street      "
            ,"Andover Court      "
            ,"Catherine Street   "
            ,"Cypress Court      "
            ,"Franklin Court     "
            ,"Grove Street       "
            ,"Willow Avenue      "
            ,"2nd Street East    "
            ,"Cedar Avenue       "
            ,"Hamilton Road      "
            ,"Route 17           "
            ,"4th Street South   "
            ,"Forest Drive       "
            ,"Madison Avenue     "
            ,"Garden Street      "
            ,"Garfield Avenue    "
            ,"9th Street         "
            ,"Augusta Drive      "
            ,"Valley View Drive  "
            ,"Devon Court        "
            ,"Oxford Road        "
            ,"Westminster Drive  "
            ,"Cemetery Road      "
            ,"Brandywine Drive   "
            ,"Cleveland Street   "
            ,"Prospect Avenue    "
            ,"B Street           "
            ,"7th Street         "
            ,"3rd Street East    "
            ,"Durham Court       "
            ,"Devonshire Drive   "
            ,"Lake Street        "
            ,"Cross Street       "
            ,"Holly Drive        "
            ,"Victoria Court     "
            ,"Riverside Drive    "
            ,"Myrtle Street      "
            ,"Route 44           "
            ,"5th Street West    "
            ,"Ann Street         "
            ,"Main Street East   "
            ,"Mechanic Street    "
            ,"Summit Avenue      "
            ,"Lincoln Street     "
            ,"Fawn Court         "
            ,"Academy Street     "
            ,"Bridle Lane        "
            ,"Court Street       "
            ,"7th Avenue         "
            ,"Route 6            "
            ,"Spruce Street      "
            ,"Magnolia Avenue    "
            ,"Linden Street      "
            ,"Broad Street       "
            ,"Edgewood Road      "
            ,"Adams Avenue       "
            ,"2nd Street West    "
            ,"Oxford Court       "
            ,"Washington Avenue  "
            ,"9th Street West    "
            ,"Evergreen Drive    "
            ,"Lantern Lane       "
            ,"Liberty Street     "
            ,"Inverness Drive    "
            ,"Bay Street         "
            ,"Durham Road        "
            ,"Center Street      "
            ,"Railroad Street    "
            ,"Forest Avenue      "
            ,"Jefferson Street   "
            ,"North Avenue       "
            ,"College Street     "
            ,"4th Street         "
            ,"Oak Street         "
            ,"Carriage Drive     "
            ,"South Street       "
            ,"White Street       "
            ,"Surrey Lane        "
            ,"Route 20           "
            ,"Circle Drive       "
            ,"Pleasant Street    "
            ,"Elizabeth Street   "
            ,"Cherry Lane        "
            ,"Sheffield Drive    "
            ,"Locust Lane        "
            ,"Olive Street       "
            ,"Maple Street       "
            ,"New Street         "
            ,"Country Lane       "
            ,"3rd Street         "
            ,"14th Street        "
            ,"Poplar Street      "
            ,"Spring Street      "
            ,"Heather Court      "
            ,"Devon Road         "
            ,"Columbia Street    "
            ,"Mill Road          "
            ,"Cardinal Drive     "
            ,"Overlook Circle    "
            ,"Ivy Court          "
            ,"Hudson Street      "
            ,"Dogwood Drive      "
            ,"Cottage Street     "
            ,"Warren Avenue      "
            ,"Church Street      "
            ,"Route 11           "
            ,"Windsor Court      "
            ,"Route 100          "
            ,"Front Street       "
            ,"Hamilton Street    "};

    public static String getStreet()
    {
        Random random = new Random();
        int val = random.nextInt(streets.length);
        return streets[val].trim();
    }
}
